### ISSUE TITLE
Import Error when using "get_pourbaix_entries"

### ISSUE THREAD

**Issue by snesnehne** [materialsvirtuallab/matgenb#24]
Using python version 3.7.1 I am trying to use the example for producing pourbaix diagrams.
The first errors I receive when importing the packages and calling "get_pourbaix_entries" are resolved upon recompiling.
`ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216`

I then get the following error upon recompiling the code below:
`# Get all pourbaix entries corresponding to the Cu-O-H chemical system.`
`entries = mpr.get_pourbaix_entries(["Cu"])`

`ImportError: cannot import name 'LinearAssignment' from 'pymatgen.optimization.linear_assignment' (unknown location)`

**Comment by shyuep** [comment]
What are you using to isntall pymatgen? If conda, try using just pip install pymatgen --upgrade

**Comment by mkhorton** [comment]
This error is usually the result of having your installed numpy not matching the version of numpy used to build the pymatgen version on PyPI.

In addition to @shyuep's suggestion, you can also try `pip install pymatgen --no-binary pymatgen --upgrade`.

**Comment by snesnehne** [comment]
Thanks for the suggestions @shyuep @mkhorton . I was able to resolve the issue by updating the my version of numpy.

However, now I receive the following error:

`MPRestError: REST query returned with error status code 403. Content: b'{"valid_response": false, "error": "API_KEY is not supplied.", "version": {"db": "2018.11", "pymatgen": "2019.3.27", "rest": "2.0"}, "created_at": "2019-04-10T23:59:36.679500"}'`

Is there a command that must be entered first in order to supply an API key?

**Comment by mkhorton** [comment]
Yes, you have to log in or create an account on materialsproject.org to get
an API key, you’ll find it on your dashboard after you log in.

This can then either be provided as an argument to MPRester or you can set
it permanently as an environment variable, more information is in the
pymatgen documentation.

**Comment by snesnehne** [comment]
Awesome, everything is working now. I appreciate it.

**Comment by mkhorton** [comment]
No problem!
