### ISSUE TITLE
Can developers update files?

### ISSUE THREAD

**Issue by thienbinh92** [materialsvirtuallab/matgenb#45]
Hi, I found that pymatgen has changed a lot [change-log](https://pymatgen.org/change_log.html), which some modules can not be found in the lastest version. May I request developers update the notebook files for convenience?

**Comment by shyuep** [comment]
Can you be specific which notebooks are giving you an error?

**Comment by thienbinh92** [comment]
Dear Prof. Ong, 
I think several files need to be updated. For example,
In file 'Basic functionality', module 'pymatgen.core' has no attribute 'Species'.  
In the file named "2013-01-01-Plotting and Analyzing a Phase Diagram using the Materials API.ipynb", 'Line2D' object has no property 'backend'
In file '2013-01-01-Plotting the electronic structure of Fe.ipynb', 'PolarAxes' object has no property 'axisbg'
In file "2016-09-08-Data-driven First Principles Methods for the Study and Design of Alkali Superionic Conductors Part 2 - Phase and Electrochemical Stability.ipynb", No module named 'pymatgen.phasediagram', module 'PDAnalyzer' is not available. 
Please help us check and update files.

**Comment by shyuep** [comment]
I just pushed a series of update. You need to install the latest pymatgen. In general, we cannot keep updating the examples except for some of the core examples. These notebooks are provided by a lot of different people over many pymatgen versions (and matplotlib versions). Some of these are very old.
