### ISSUE TITLE
[Missing notebook]: The `2013-01-01-Bandstructure of NiO` is missing

### ISSUE THREAD

**Issue by DanielYang59** [materialsvirtuallab/matgenb#59]
The `2013-01-01-Bandstructure of NiO.ipynb` is removed in 013e371fd13bb165c7d681eed3d07aa30148254c but the hyperlink is still kept in the homepage. I'm not sure if this removal is accidental or intended?

<img width="1039" alt="image" src="https://github.com/user-attachments/assets/56e9607a-348d-4d54-84fa-8ec98cf60e81">

**Comment by shyuep** [comment]
Intended. There is no way to test the notebook and the features are repeated in the plotting bandstructure notebook.

**Comment by DanielYang59** [comment]
Thanks for the input. I would push a PR to remove it from the homepage then :)
