### ISSUE TITLE
`pymacy` package?

### ISSUE THREAD

**Issue by dwinston** [materialsvirtuallab/matgenb#9]
The [2018-03-09-Reaction Diagram Construction](https://github.com/materialsvirtuallab/matgenb/blob/ec8a5aa54d97c00e7439de0c9c2a907a18bf73aa/notebooks/2018-03-09-Reaction%20Diagram%20Construction.ipynb) notebook has the line
```python
from pymacy.bim.thermo import ReactionAnalysis
```
in the first code cell, but I couldn't find a `pymacy` package on PyPI. Could you amend the notebook with instructions on how to install that package?

**Comment by shyuep** [comment]
THanks for letting me know. This escaped my attention. @paulgholin will move the relevant code to pymatgen and fix.

**Comment by shyuep** [comment]
This has been fixed with the latest pmg and matgenb release.
